### ISSUE TITLE
VirusTotal Scan... afraid to install.

### ISSUE THREAD

**Issue by victorcatalin** [DeskTranslate/DeskTranslate#25]
https://www.virustotal.com/gui/file/6728efad2b8a0d6b3b2c24251ed145b6f2f6ffb699b354997aea3f3f5d1a9516 

Why so many red flags, bro? :(

**Comment by gerardtwk** [comment]
Hi,

The installer is created using the software called "NSIS", and it is known to have false positives as stated here:
https://nsis.sourceforge.io/NSIS_False_Positives

To get an accurate result from VirusTotal, you should upload the .exe file that is unpacked from the installer.
