### ISSUE TITLE
English to Hebrew doesn't work

### ISSUE THREAD

**Issue by Sigarya** [DeskTranslate/DeskTranslate#5]
It just shows the English text without translating:
![‏‏צילום מסך (15)](https://user-images.githubusercontent.com/79363716/192013431-ab02df86-88ae-4ed8-9801-40d9c36820b8.png)

It works the other way around:
![‏‏צילום מסך (16)](https://user-images.githubusercontent.com/79363716/192013494-dbf4711e-d35b-4380-818a-a8422fea1088.png)

**Comment by KyooSikLee** [comment]
![tesseract-ocr-w64-setup-5 3 0 20221222_axZsLbEJZj](https://user-images.githubusercontent.com/26744641/218263129-c3e95e60-2688-478f-a1f8-963a36c962e0.png)
When installing Tesseract-OCR, did you check additional language data? After adding additional data, mine worked

**Comment by Sigarya** [comment]
I tried installing it again like you said, but it still shows the original text instead of the Hebrew translation.
Did you manage to get it to translate to Hebrew?
***@***.***

**Comment by hua-lun** [comment]
![Capture](https://github.com/DeskTranslate/DeskTranslate/assets/45708294/7b9be59e-166a-4678-b7c9-db22c33ae6c1)

Add more langauges for translation
