### ISSUE TITLE
If this is for windows only...

### ISSUE THREAD

**Issue by DiabloStorm** [DeskTranslate/DeskTranslate#7]
Can you just please make a windows installer? For the DumDums like me? Because this is not working. I've likely made mistakes. I had the latest version of tesseract installed, it won't translate, so, yes you specifically mention 5.0, but which one? So I tried what looked like the stable release of 5.0. I literally only want to use this for Japanese, but your instructions insist I download nearly a gigabyte of languages. So upon reinstalling (3rd time now actually) I get an error for every single language and now your program is looking in a drive for tesseract I wouldn't have installed it to.

**Comment by hua-lun** [comment]
Hi @DiabloStorm 

Do consider downloading our latest version of the installer - https://github.com/DeskTranslate/DeskTranslate/releases/tag/1.1a

After completing the setup for DeskTranslate, another installer for Tesseract will be launched.
Components: ScrollView, Training Tools and Shortcut creation are not required. Feel free to uncheck them to reduce download size.
![Capture3](https://github.com/DeskTranslate/DeskTranslate/assets/45708294/4bd16009-f509-47cf-8a2e-db9353acf4b1)

If only 1 translation language is needed i.e. English to / from Japanese, check the corresponding data.

In this case, under both the `Additional script data (download)` and `Additional language data (download)`, select 
- Japanese
- Japanese (Vertical)
![Capture2](https://github.com/DeskTranslate/DeskTranslate/assets/45708294/69435085-f858-467e-b876-13a86e8d0a23)

In total, 5 checkboxes need to be checked to use it for Japanese translation. 

I hope this helps!

**Comment by Mostidioticperson** [comment]
> Hi @DiabloStorm
> 
> Do consider downloading our latest version of the installer - https://github.com/DeskTranslate/DeskTranslate/releases/tag/1.1a
> 
> After completing the setup for DeskTranslate, another installer for Tesseract will be launched. Components: ScrollView, Training Tools and Shortcut creation are not required. Feel free to uncheck them to reduce download size. ![Capture3](https://user-images.githubusercontent.com/45708294/257043381-4bd16009-f509-47cf-8a2e-db9353acf4b1.PNG)
> 
> If only 1 translation language is needed i.e. English to / from Japanese, check the corresponding data.
> 
> In this case, under both the `Additional script data (download)` and `Additional language data (download)`, select
> 
> * Japanese
> * Japanese (Vertical)
>   ![Capture2](https://user-images.githubusercontent.com/45708294/257043480-69435085-f858-467e-b876-13a86e8d0a23.PNG)
> 
> In total, 5 checkboxes need to be checked to use it for Japanese translation.
> 
> I hope this helps!

Hello sorry im also too dumb to understand stuffs but I followed your instructions and selected Korean which I want to read but my app is not working.

**Comment by EthanLux** [comment]
Good day @hua-lun,
I also followed the instructions, but Desktranslate also wont work for me.

After the installment of Tesseract and choosing the corresponding components (english, Japanese, japanese(vertical))
I can start the programm and select the languages and set the borders: 
![image](https://github.com/DeskTranslate/DeskTranslate/assets/142596713/0a18e72c-012e-4b3c-a4a6-a2468ec15701)
and I still see no translation 
![image](https://github.com/DeskTranslate/DeskTranslate/assets/142596713/2e8d6065-9386-460b-89f7-2a8b53ae4b43)
Help is really appreciated

**Comment by hua-lun** [comment]
@Mostidioticperson 

Hi 

Can you provide some screenshots of the page you want to read / translate?

**Comment by hua-lun** [comment]
> Good day @hua-lun,
> 
> I also followed the instructions, but Desktranslate also wont work for me.
> 
> 
> 
> After the installment of Tesseract and choosing the corresponding components (english, Japanese, japanese(vertical))
> 
> I can start the programm and select the languages and set the borders: 
> 
> ![image](https://github.com/DeskTranslate/DeskTranslate/assets/142596713/0a18e72c-012e-4b3c-a4a6-a2468ec15701)
> 
> and I still see no translation 
> 
> ![image](https://github.com/DeskTranslate/DeskTranslate/assets/142596713/2e8d6065-9386-460b-89f7-2a8b53ae4b43)
> 
> Help is really appreciated

Hi @EthanLux 

Did you press the **translate** button after selecting the borders? 

After pressing **translate**, a pop up window should appear. The translated text will be shown automatically.

**Comment by hua-lun** [comment]
@Mostidioticperson 
@EthanLux 

This is our [user guide](https://desktranslate.github.io/DeskTranslate/UserGuide.html)

Do check it out for a detailed walkthrough of the features 

Thank you for trying our app!

**Comment by hua-lun** [comment]
@EthanLux 

I noticed in your previous comment:
> After the installment of Tesseract and choosing the corresponding components (english, Japanese, japanese(vertical))

It seems that you've missed 2 more components. 
As stated, "5 checkboxes need to be checked to use it for Japanese translation." 

This is the following:
1. Language Data
2. Additional script data (download) - **Japanese (Vertical)**
3. Additional script data (download) - **Japanese**
4. Additional language data (download) -**Japanese (Vertical)**
5. Additional language data (download) -**Japanese**

Also ensure that the installation path is when installing Tesseract - `C:\Program Files` 

As such, I suggest running the `DeskTranslateInstaller.exe` again to ensure all components are installed. 

Do reach out if you need more help to set it up.

**Comment by EthanLux** [comment]
Hello again,
I am so sorry but it still won't work.
All my steps so far (I even tried several reinstallments and installed them on):

![image](https://github.com/DeskTranslate/DeskTranslate/assets/142596713/797fffe4-0955-4b8b-aaa4-5bd5699d3870)

![image](https://github.com/DeskTranslate/DeskTranslate/assets/142596713/b4e12eac-db9c-40bc-8866-00355d07c34f)
![image](https://github.com/DeskTranslate/DeskTranslate/assets/142596713/8ba414a9-5c6c-491f-bbf1-f7c9596c20e3)

Tesseract:
![image](https://github.com/DeskTranslate/DeskTranslate/assets/142596713/7cc94235-b92f-47b0-8f2b-c5b51aa68dbe)

On Additional script and language data I choose Japanese and Japanese vertical
![image](https://github.com/DeskTranslate/DeskTranslate/assets/142596713/a3da0a82-55b2-4bda-91b0-6be65939d48d)
![image](https://github.com/DeskTranslate/DeskTranslate/assets/142596713/ed69b75c-53dc-4f5e-b84f-c374dc3a3be2)

After starting DeskTranslate:
-Choosing languages
-Select borders
-clicked on "Translate"
=> Window "DeskTranslator - Translating" opens but no translated text shown.
![image](https://github.com/DeskTranslate/DeskTranslate/assets/142596713/4cb51500-fd52-48ad-87e0-9d4fb60bb919)


Thank you for taking your time.

**Comment by hua-lun** [comment]
Hi @EthanLux 

Thank you for providing screenshots. Most of the steps seem to be correct. 
But there's one part to take note of:

 ![image](https://user-images.githubusercontent.com/142596713/261791390-ed69b75c-53dc-4f5e-b84f-c374dc3a3be2.png)

In this part, the **Destination Folder** needs to be in: `C:\Program Files\Tesseract-OCR`
This is where our program finds it. 

As such, you'll have to restart the installation. 
- Click *Yes* / *Ok*,  when prompted to uninstall Tesseract in the existing folder. 
- Check the necessary parts required and make sure to change **Destination Folder** to `C:\Program Files\Tesseract-OCR`

I believe it's possible to replace, copy and paste `C:\Program Files\Tesseract-OCR` into the text box. 
Alternatively, click Browse and find this folder (located in C: drive) `C:\Program Files\Tesseract-OCR`

**Comment by EthanLux** [comment]
Thank you!! It's working!
