### ISSUE TITLE
Requirements.txt doesn't work with Python 3.11

### ISSUE THREAD

**Issue by jialiang** [DeskTranslate/DeskTranslate#8]
The requirements.txt provided doesn't work with Python 3.11.

After changing it to the following, the libraries install successfully and so far the program works: 

```
googletrans==3.1.0a0
deep_translator
pytesseract
pyttsx3
PyGetWindow==0.0.9
numpy==1.24.3
opencv-python==4.7.0.72
Pillow==9.5.0
pyperclip==1.8.1
PyQt5==5.15.9
PyQt5-sip==12.12.1
PyRect==0.1.4
```

**Comment by Xaffekt** [comment]
you just saved me so much headache lol thank you
